myapp/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.home, name='home'),
    path('create-voting/', views.vote ,name='create-voting'),
    path('vote/home/', views.home, name='home'),
    path('vote/success/', views.vote_success, name='vote_success'),
    path('vote/', views.combined_view, name='vote'),
    path('select_voting/', views.voting, name='select_voting'),
    path('services/', views.services, name='services'),
    path('create/', views.create, name='create'),
    path('results/',views.graph_view,name='results'),
    path('to_create/',views.to_create,name='to_create'),
    path('contact/',views.contact,name='contact'),
    path('about/',views.about,name='about')
]

voting/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('create-voting/', include('myapp.urls')),
    path('try/', include('myapp.urls')),
    path('vote/', include('myapp.urls')),
    path('vote/success/',include('myapp.urls')),
    # path('graph/',include('myapp.urls') ),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models

class Image(models.Model):
    backgroundimg = models.ImageField(upload_to="backgroundimg")
    brandtitle = models.CharField(max_length=200)
    name = models.CharField(max_length=200)
    discription = models.CharField(max_length=200)
    photo = models.ImageField(upload_to="myimage")
    votetitle = models.CharField(max_length=200)
    candidate1 = models.ImageField(upload_to="candidate1")
    name_candidate1 = models.CharField(max_length=200)
    candidate2 = models.ImageField(upload_to="candidate2")
    name_candidate2 = models.CharField(max_length=200)
    candidate3 = models.ImageField(upload_to="candidate3")
    name_candidate3 = models.CharField(max_length=200)
    candidate4 = models.ImageField(upload_to="candidate4")
    name_candidate4 = models.CharField(max_length=200)
    candidate5 = models.ImageField(upload_to="candidate5")
    name_candidate5 = models.CharField(max_length=200)
    candidate6 = models.ImageField(upload_to="candidate6")
    name_candidate6 = models.CharField(max_length=200)
    footerimg = models.ImageField(upload_to="footerimg")
    footerbg = models.ImageField(upload_to="footerimg")
    instagramlink = models.CharField(max_length=200)
    facebooklink = models.CharField(max_length=200)
    youtubelink = models.CharField(max_length=200)
    twitterlink = models.CharField(max_length=200)
    date = models.DateField(auto_now_add=True)
    
    
    
    
    
from django.db import models

class Vote(models.Model):
    option1_votes = models.PositiveIntegerField(default=0)
    option2_votes = models.PositiveIntegerField(default=0)
    option3_votes = models.PositiveIntegerField(default=0)
    option4_votes = models.PositiveIntegerField(default=0)
    option5_votes = models.PositiveIntegerField(default=0)
    option6_votes = models.PositiveIntegerField(default=0)
    total_votes = models.PositiveIntegerField(default=0)
    option1_percentage = models.FloatField(default=0)
    option2_percentage = models.FloatField(default=0)
    option3_percentage = models.FloatField(default=0)
    option4_percentage = models.FloatField(default=0)
    option5_percentage = models.FloatField(default=0)
    option6_percentage = models.FloatField(default=0)




myapp/forms.py
from django import forms
from .models import Image

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = '__all__'
        labels = {'photo':'','candidate1': '','candidate2': '','candidate3': '','candidate4': '','candidate5': '','candidate6': '','backgroundimg':'','footerimg':'','footerbg':''}
        
        
from django import forms

class VoteForm(forms.Form):
    candidate = forms.ChoiceField(choices=(
        ('option1', 'Option 1'),
        ('option2', 'Option 2'),
        ('option3', 'Option 3'),
        ('option4', 'Option 4'),
        ('option5', 'Option 5'),
        ('option6', 'Option 6'),
    ), widget=forms.RadioSelect)

myapp/views.py
from django.shortcuts import render
from .forms import ImageForm
from .models import Image
from myapp.models import Image
from django.shortcuts import render, redirect
from .models import Vote
from .forms import VoteForm
from django.http import HttpResponseRedirect

# Create your views here.

def home (request):
    return render (request,'myapp/index.html')

# def voting (request):
    
#     return render (request , 'myapp/vote.html')


def voting (request):
    latest_id = Image.objects.latest('id').id
    latest_data = Image.objects.get(id=latest_id)
    return render(request, 'myapp/vote.html', {'latest_data': latest_data})

# def voting (request):
#     latest_entry = Image.objects.latest('id')
#     context = {
#         'latest_entry': latest_entry
#     }
#     return render(request, 'myapp/voting.html')














def services (request):
    return render (request , 'myapp/services.html')

def create (request):
    return render (request , 'myapp/create.html')


# def vote (request):
#     if request.method == "POST":
#         brandtitle = request.POST.get("brandtitle")
#         name = request.POST.get("name")
#         votetitle = request.POST.get("votetitle")
#         name_candidate1 = request.POST.get("name_candidate1")
#         name_candidate2 = request.POST.get("name_candidate2")
#         name_candidate3 = request.POST.get("name_candidate3")
#         name_candidate4 = request.POST.get("name_candidate4")
#         name_candidate5 = request.POST.get("name_candidate5")
#         name_candidate6 = request.POST.get("name_candidate6")
#         instagramlink = request.POST.get("instagramlink")
#         facebooklink = request.POST.get("facebooklink")
#         youtubelink = request.POST.get("youtubelink")
#         twitterlink  = request.POST.get("twitterlink ")
#         discription= request.POST.get("discription")
#         vote = Image (name=name , discription=discription,name_candidate1=name_candidate1,name_candidate2=name_candidate2,name_candidate3=name_candidate3,name_candidate4=name_candidate4,name_candidate5=name_candidate5,name_candidate6=name_candidate6, votetitle =votetitle ,brandtitle=brandtitle,instagramlink=instagramlink,facebooklink=facebooklink,youtubelink=youtubelink,twitterlink=twitterlink)
#         form = ImageForm (request.POST , request.FILES)
#         if form.is_valid():
#             form.save()
#     form = ImageForm()
#     img = Image.objects.all()
#     return render (request , 'myapp/create_vote.html')







def vote (request):
    if request.method == "POST":
        brandtitle = request.POST.get("brandtitle")
        name = request.POST.get("name")
        votetitle = request.POST.get("votetitle")
        name_candidate1 = request.POST.get("name_candidate1")
        name_candidate2 = request.POST.get("name_candidate2")
        name_candidate3 = request.POST.get("name_candidate3")
        name_candidate4 = request.POST.get("name_candidate4")
        name_candidate5 = request.POST.get("name_candidate5")
        name_candidate6 = request.POST.get("name_candidate6")
        instagramlink = request.POST.get("instagramlink")
        facebooklink = request.POST.get("facebooklink")
        youtubelink = request.POST.get("youtubelink")
        twitterlink  = request.POST.get("twitterlink ")
        discription= request.POST.get("discription")
        vote = Image (name=name , discription=discription,name_candidate1=name_candidate1,name_candidate2=name_candidate2,name_candidate3=name_candidate3,name_candidate4=name_candidate4,name_candidate5=name_candidate5,name_candidate6=name_candidate6, votetitle =votetitle ,brandtitle=brandtitle,instagramlink=instagramlink,facebooklink=facebooklink,youtubelink=youtubelink,twitterlink=twitterlink)
        form = ImageForm (request.POST , request.FILES)
        if form.is_valid():
            form.save()
            return render (request , 'myapp/created_succes.html')
        else:
            return render (request , 'myapp/created_error.html')
    form = ImageForm()
    img = Image.objects.all()
    return render (request , 'myapp/create_vote.html')

def about (request):
    return render(request, 'myapp/about.html')

def contact (request):
    return render(request, 'myapp/contact.html')

def to_create(request):
    return render(request, 'myapp/all_create.html')

def vote_success(request):
    return render(request, 'myapp/vote_success.html')

def combined_view(request):
    latest_entry = Image.objects.latest('id')

    # Retrieve the vote counts from the database
    vote = Vote.objects.first()  # Assuming there is only one row in the Vote table
    total_votes = vote.total_votes

    # Calculate the vote percentages
    option1_percentage = (vote.option1_votes / total_votes) * 100
    option2_percentage = (vote.option2_votes / total_votes) * 100
    option3_percentage = (vote.option3_votes / total_votes) * 100
    option4_percentage = (vote.option4_votes / total_votes) * 100
    option5_percentage = (vote.option5_votes / total_votes) * 100
    option6_percentage = (vote.option6_votes / total_votes) * 100

    if request.method == 'POST':
        form = VoteForm(request.POST)
        if form.is_valid():
            candidate = form.cleaned_data['candidate']
            setattr(vote, f'{candidate}_votes', getattr(vote, f'{candidate}_votes') + 1)
            vote.total_votes += 1
            vote.save()
            option1_percentage = (vote.option1_votes / vote.total_votes) * 100
            option2_percentage = (vote.option2_votes / vote.total_votes) * 100
            option3_percentage = (vote.option3_votes / vote.total_votes) * 100
            option4_percentage = (vote.option4_votes / vote.total_votes) * 100
            option5_percentage = (vote.option5_votes / vote.total_votes) * 100
            option6_percentage = (vote.option6_votes / vote.total_votes) * 100
            return redirect('vote_success')
    else:
        form = VoteForm()

    context = {
        'latest_entry': latest_entry,
        'form': form,
        'option1_percentage': option1_percentage,
        'option2_percentage': option2_percentage,
        'option3_percentage': option3_percentage,
        'option4_percentage': option4_percentage,
        'option5_percentage': option5_percentage,
        'option6_percentage': option6_percentage,
    }

    return render(request, 'myapp/voting_page.html', context)



def graph_view(request):
    latest_entry = Image.objects.latest('id')

    # Retrieve the vote counts from the database
    vote = Vote.objects.first()  # Assuming there is only one row in the Vote table
    total_votes = vote.total_votes

    # Calculate the vote percentages
    option1_percentage = (vote.option1_votes / total_votes) * 100
    option2_percentage = (vote.option2_votes / total_votes) * 100
    option3_percentage = (vote.option3_votes / total_votes) * 100
    option4_percentage = (vote.option4_votes / total_votes) * 100
    option5_percentage = (vote.option5_votes / total_votes) * 100
    option6_percentage = (vote.option6_votes / total_votes) * 100

    if request.method == 'POST':
        form = VoteForm(request.POST)
        if form.is_valid():
            candidate = form.cleaned_data['candidate']
            setattr(vote, f'{candidate}_votes', getattr(vote, f'{candidate}_votes') + 1)
            vote.total_votes += 1
            vote.save()
            option1_percentage = (vote.option1_votes / vote.total_votes) * 100
            option2_percentage = (vote.option2_votes / vote.total_votes) * 100
            option3_percentage = (vote.option3_votes / vote.total_votes) * 100
            option4_percentage = (vote.option4_votes / vote.total_votes) * 100
            option5_percentage = (vote.option5_votes / vote.total_votes) * 100
            option6_percentage = (vote.option6_votes / vote.total_votes) * 100
            return redirect('vote_success')
    else:
        form = VoteForm()

    context = {
        'latest_entry': latest_entry,
        'form': form,
        'option1_percentage': option1_percentage,
        'option2_percentage': option2_percentage,
        'option3_percentage': option3_percentage,
        'option4_percentage': option4_percentage,
        'option5_percentage': option5_percentage,
        'option6_percentage': option6_percentage,
    }

    return render(request, 'myapp/results.html', context)

templates/myapp/about.html
{% extends 'myapp/base.html' %}
{% block about %}
<style>
    .about{
        padding-top: 130px;
        padding-bottom: 50px;
        align-items: center;
        justify-content: center;
        display: flex;
    }
    .about-container{
        margin-left: auto;
        margin-right: auto;
        width: 80%;
        height: 80vh;
        box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.5); 
        border-radius: 10px;
        text-align: center;
        display: flex;
        flex-direction: column;
        align-items: center;
        
    }
    .about-container >h1{
        margin-top: 30px;
        font-size: 3rem;
        color: rgb(34, 34, 34);
    }
    .about-container >p{
        width: 60vw;
        margin-top: 3vw;
        color: rgba(38, 38, 38, 0.913);
    }
    .about_contact{
        margin-top: 70px;
    }
    button{
        border-color: transparent;
        font-weight: 500;
        background-color: #01CFFF;
        font-size: 1.5rem;
        width: 20vw;
        height: 7vh;
        border-radius: 10px;
        box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.5); 
    }
    .contactbtn:hover {
        cursor: pointer;
        background-color: transparent;
        border-color: #fbdc16;
        border-width: 2px;
    }
</style>


<div class="about">
    <div class="about-container">
        <h1>About-Us</h1>
        <p>VoteLytics is an innovative next-generation voting system designed to revolutionize the voting experience. Its primary focus is on delivering a seamless and user-friendly interface that ensures a perfect voting process. With VoteLytics, you have the flexibility to personalize your voting system by incorporating custom images, custom social media links, and even a customized background, allowing you to create a visually appealing and engaging platform.</p>
        <p>One of the standout features of VoteLytics is its real-time result calculation. Gone are the days of waiting anxiously for the outcome of a vote. With VoteLytics, you can witness the results being calculated instantly and presented graphically. This dynamic approach not only provides transparency but also enhances the overall voting experience.</p>
        <p>By prioritizing user experience, VoteLytics aims to redefine the way people engage with voting systems. The seamless integration of intuitive design elements and interactive features ensures that users have a smooth and enjoyable experience while casting their votes. Whether it's a small-scale election or a large-scale survey, VoteLytics caters to diverse voting needs while upholding the highest standards of user satisfaction.</p>
        <p>With VoteLytics, you can be confident that your voting system will captivate participants with its visually appealing interface, convenient features, and efficient result visualization. It empowers you to create a voting experience that is not only efficient and accurate but also memorable and engaging for all stakeholders involved.</p>
        <div class="about_contact"><a href="{% url 'contact' %}"><button class="contactbtn">Contact</button></a></div>
    </div>
    

</div>

{% endblock about %}

templates/myapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    {% load static %}
	  <link href="{% static 'css/hello.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Font+Name&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/e2c728a258.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-EvQ/dN7IkzN4jzDwS0GvMhpThYX1HzlzMznN6nAaOTJPej6Uksi7L+JnYYkSr+G2" crossorigin="anonymous">
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <!-- <script src="https://kit.fontawesome.com/e2c728a258.js" crossorigin="anonymous"></script> -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VoteLytics</title>
</head>
<body>
    <nav class="navbar">
        <img src="{% static 'img/logo.png' %}" height="40px" alt="">
        <ul>
            <a href="{% url 'home' %}"><li class="#">Home</li></a>
            <a href="{% url 'select_voting' %}"><li class="#">Vote</li></a>
            <a href="{% url 'services' %}"><li class="#">Services</li></a>
            <a href="{% url 'create' %}"><li class="#">Create Voting</li></a>
            <a href="{% url 'about' %}"><li class="#">About</li></a>
            <a href="{% url 'contact' %}"><li class="#">Contact</li></a>
        </ul>
    </nav>
    {% block select_voting %}{% endblock select_voting %}
    {% block services %}{% endblock services %}
    {% block create %}{% endblock create %}
    {% block created_success %}{% endblock created_success %}
    {% block created_error %}{% endblock created_error %}
    {% block vote_success %}{% endblock vote_success %}
    {% block results %}{% endblock results %}
    {% block to_create %}{% endblock to_create %}
    {% block about %}{% endblock about %}
    {% block contact %}{% endblock contact %}
    <div class="page6" id="contact">
        <div class="footer">
            <footer class="footer-distributed">

                <div class="footer-left">
              
                  <h3>VoteLytic Pvt Ltd<span><img style="height: 20vh;" src="../../assets/Images/logp.png" alt=""></span></h3>
              
              
                  <p class="footer-company-name">VoteLytic Pvt Ltd © 2023</p>
                </div>
              
                <div class="footer-center">
              
                  <div>
                    <i class="fa fa-map-marker"></i>
                    <p><span>Chitkara University</span> Rajpura Punjab, India</p>
                  </div>
              
                  <div>
                    <i class="fa fa-phone"></i>
                    <p>+91.1234567890</p>
                  </div>
              
                  <div>
                    <i class="fa fa-envelope"></i>
                    <p><a href="mailto:support@company.com">support@company.com</a></p>
                  </div>
              
                </div>
              
                <div class="footer-right">
              
                  <p style="color: white;" class="footer-company-about">
                    <span>About the company</span>
                    Vote Lytic is a voting organization company that creates and manages online voting systems. We handle customer databases and provide result presentation on our website.
                  </p>
              
                  <div class="footer-icons">
              
                    <a href="#"><i class="fa fa-facebook"></i></a>
                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-linkedin"></i></a>
                    <a href="#"><i class="fa fa-github"></i></a>
              
                  </div>
              
                </div>
              
              </footer>
              
        </div>
    </div>
</body>
</html>

templates/myapp/create_vote.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	{% load static %}
	<link href="{% static 'css/create_vote.css' %}" rel="stylesheet">  
	<link rel="shortcut icon" href="footer-logo.png" type="image/x-icon">
    <title>VoteLytics</title>
</head>

<body>
	<form action="" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{form}}
		<div class="nav">
			<input type="checkbox" id="nav-check">
			<div class="nav-header">
			<div class="nav-title">
				<input class="brandtitle" type="text" id="brandtitle" name="brandtitle" placeholder="Brand Name" required></b>
			</div>
			</div>
			<div class="nav-btn">
			<label for="nav-check">
				<span></span>
				<span></span>
				<span></span>
			</label>
			</div>
			
			<div class="nav-links">
			<a href="#" > *****</a>
			<a href="#" > *****</a>
			<a href="#" > *****</a>
			<a href="#" > *****</a>
			</div>
		</div>

		<div class="page1" id="page1">
			
			<div class="page1-left">
				<div class="page1-left-heading">
					<h2>Vote your</h2>
					<h1><span class="highlight">FAVORITE </span></h1>
					<h2><input class="name" type="text" id="name" name="name" placeholder="Name" required></h2>
				</div>
			<p>
				<textarea class="discription" name="discription" id="discription" placeholder="Short Discription (Not more then 40 words)" rows="6"></textarea><br><br>
			</p>
			</div>
			<div class="page1-right">
				<div class="big-boss-logo-img" >
					<i class="fa-solid fa-layer-group"></i>
					<label for="logoimg" class="custom-logoimg-btn">
						<i class="fa-solid fa-upload"></i>   Upload Image
					</label>
					<input type="file" name="photo" accept="image/*" required="" id="logoimg" class="logoimg" >
				</div>
				
				<!-- #007F86 -->

			</div>
		</div>
		<div class="page2" id="page2">
			<main>
				<div class="vote-heading">
					<h3>Voting Title</h3>
					<div class="votetitle-input">
						<input class="votetitle" type="text" id="votetitle" name="votetitle" placeholder="Eg: Vote for Your Favorite Candidate" required>
					</div>
				<!-- <h3>Vote for Your Favorite Candidate</h3> -->
				</div>
					<div class="card-container">
						<div class="card-container1">
							<div class="card">
								<div class="card-image">
									<input type="file" name="candidate1" accept="image/*" required="" id="id_photo" class="input-img" >
									<ion-icon name="image-outline"></ion-icon>
								</div>
								<div class="card-content">
									<label for="candidate1"><i class="fa-solid fa-user"></i><input type="text" id="name" name="name_candidate1" placeholder= 'Candidate Name' required></label>
								</div>
							</div>
							<div class="card">
								<div class="card-image">
									<input type="file" name="candidate2" accept="image/*" required="" id="id_photo" class="input-img" >
									<ion-icon name="image-outline"></ion-icon>
								</div>
								<div class="card-content">
									<label for="candidate2"><i class="fa-solid fa-user"></i><input type="text" id="name" name="name_candidate2" placeholder= 'Candidate Name' required></label>
								</div>
							</div>
							<div class="card">
								<div class="card-image">
									<input type="file" name="candidate3" accept="image/*" required="" id="id_photo" class="input-img" >
									<ion-icon name="image-outline"></ion-icon>
								</div>
								<div class="card-content">
									<label for="candidate3"><i class="fa-solid fa-user"></i><input type="text" id="name" name="name_candidate3" placeholder= 'Candidate Name' required></label>
								</div>
							</div>
						</div>

						<div class="card-container2">
							<div class="card">
								<div class="card-image">
									<input type="file" name="candidate4" accept="image/*" required="" id="id_photo" class="input-img" >
									<ion-icon name="image-outline"></ion-icon>
								</div>
								<div class="card-content">
									<label for="candidate4"><i class="fa-solid fa-user"></i><input type="text" id="name" name="name_candidate4" placeholder= 'Candidate Name' required></label>
								</div>
							</div>
							<div class="card">
								<div class="card-image">
									<input type="file" name="candidate5" accept="image/*" required="" id="id_photo" class="input-img" >
									<ion-icon name="image-outline"></ion-icon>
								</div>
								<div class="card-content">
									<label for="candidate5"><i class="fa-solid fa-user"></i><input type="text" id="name" name="name_candidate5" placeholder= 'Candidate Name' required></label>
								</div>
							</div>
							<div class="card">
								<div class="card-image">
									<input type="file" name="candidate6" accept="image/*" required="" id="id_photo" class="input-img" >
									<ion-icon name="image-outline"></ion-icon>
								</div>
								<div class="card-content">
									<label for="candidate6" ><i class="fa-solid fa-user"></i><input type="text" id="name" name="name_candidate6" placeholder= 'Candidate Name'  required></label>
								</div>
							</div>
						</div>
					</div>
			</main>
		</div>
		<div class="page3">
			<div class="background-image">
				<div class="mainpagebg">
					<div class="mainpage-inputheading">
						<h1>Full Page Background</h1>
					</div>
					<div class="mainpage-inputbox">
						<input type="file" name="backgroundimg" accept="image/*" required="" id="backgroundimg" class="backgroundimg" >
					</div>
				</div>
				<div class="footerpagebg">
					<div class="footer-inputheading">
						<h1>Footer Page Background</h1>
					</div>
					<div class="footer-inputbox">
						<input type="file" name="footerbg" accept="image/*" required="" id="footerbg" class="footerbg">
					</div>
				</div>
			</div>
		</div>
		<div class="page4" id="page4">
			<div class="page4-left">
				<div class="content">
					<div class="heading">
						<h1>********</h1>
						<h1>********</h1>
					</div>
					<div class="watch-logo">
						<h2>Watch now on</h2>
						<div class="watch-logo-image">
							<img src="{% static 'colors-logo.svg' %}" alt="My image">
							<img src="{% static 'voot-logo.png' %}" alt="My image">
						</div>
					</div>
				</div>
			</div>
			<div class="page4-right">
				<div class="footer-container">
					<div class="footer-mainimage">
						<i class="fa-solid fa-layer-group"></i>
						<label for="footerimg" class="footer-image-custom">
							<i class="fa-solid fa-upload"></i>   Upload Image
						</label>
						<input type="file" name="footerimg" accept="image/*" required="" id="footerimg" class="footerimg">
					</div>
					<div class="social-media-page4">
						<h2>Social Media Links</h2>
						<div class="socil-media-icons">
							<div class="instagram">
								<i class="fa-brands fa-instagram"></i><input class="instagramlink" type="text" id="instagramlink" name="instagramlink" placeholder="Instagram Link" required>
							</div>
							<div class="facebook">
								<i class="fa-brands fa-facebook"></i><input class="facebooklink" type="text" id="facebooklink" name="facebooklink" placeholder="Facebook Link" required>
							</div>
							<div class="youtube">
								<i class="fa-brands fa-youtube"></i><input class="youtubelink" type="text" id="youtubelink" name="youtubelink" placeholder="YouTube Link" required>
							</div>
							<div class="twitter">
								<i class="fa-brands fa-twitter"></i><input class="twitterlink" type="text" id="twitterlink" name="twitterlink" placeholder="Twitter Link" required>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="submit-btn">
			<i class="fa-solid fa-layer-group"></i>
			<div class="full-submitbtn">
				<i class="fa-solid fa-upload"></i>
				<input type="submit" value="Upload" class="form-submit">
			</div>
			<i class="fa-solid fa-database"></i>
		</div>
	</form>

	<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
	<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
	<script src="https://kit.fontawesome.com/e2c728a258.js" crossorigin="anonymous"></script>
</body>
</html>

templates/myapp/created_error.html
{% extends 'myapp/base.html' %}
{% block created_error %}
<style>
    .created1{
        padding-top: 100px;
        text-align: center;
        align-items: center;
        justify-content: center;
        padding-bottom: 90px;
        display: flex;
    }
    .created1-container{
        margin: auto;
        text-align: center;
        align-items: center;
        justify-content: center;
        width: 80%;
        height: 80vh;
        background-color: white;
        box-shadow: 0px 7px 10px rgba(0, 0, 0, 0.5); 
        border-radius: 10px;
        display: flex;
        flex-direction: column;
        overflow: hidden;
    }
    .created1-content{
        width: 100%;
        margin: auto;
        height: 65%;
    }
    .created1-content h1{
        margin-top: 40px;
        font-size: 2.5rem;
        color: rgb(106, 106, 106);
    }
    .created1-content h2{
        font-size: 2rem;
        color: rgb(106, 106, 106);
    }

    .emoji{
        font-size: 10rem;
    }
    .created1-buttons{
        width: 100%;
        height: 35%;
        border-radius: 10px;
        background-color: rgba(218, 218, 218, 0.633);
        box-shadow: 0 0px 10px rgba(0, 0, 0, 0.8);
       
    }

    .again{
        width: 50%;
        margin: auto;
        margin-top: 7%;
        height: 5vh;
        font-size: 1.5rem;
        border-radius: 15px;
        border-color: transparent;
        background-color: #fee01a;
        color: rgb(69, 69, 69);
        box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.5);
        cursor: pointer; 
    }
    .again:hover{
        border-width: 2px;
        border-color: #fee01a;
        background-color: transparent;
    }


</style>
    <div class="created1">
        <div class="created1-container">
            <div class="created1-content">
                <h1>Sorry</h1>
                <div class="emoji">&#128557;</div>
                <h2>Your voting system has some error Try Again!</h2>
            </div>
            <div class="created1-buttons">
                <a href="{% url 'vote' %}"><button class="again">Create the page again</button></a>
            </div>
        </div>
    </div>
{% endblock created_error %}